In [1]:
import requests
from bs4 import BeautifulSoup as BS
import pandas as pd
from random import randint
from time import sleep

In [27]:
# Create fruit tree names Dataframe
fruit_trees_df = pd.DataFrame()

# Need to iterate through fruit category and append to URL.
fruit_pages = ['Apple','Peach','Plum','Pear','Nectarine','Cherry','Apricot']

# iterate through fruit_pages category names, append to url AFTER zone iteration.
for cat in fruit_pages:

# Iterate through zones 3-9 pages
    for zone in range(3,4):
        zone_num = str(zone)
        base_url = f'https://www.cumminsnursery.com/buy-trees/index.php?type=tree&year=year1&view=list&zone=' + zone_num + '&category=' + cat + '&subcategory='
        print(base_url)
        response = requests.get(base_url)
        soup = BS(response.text)
        tag_text = soup.find('table', attrs={'class':'ui celled table'}).find_all('a')
        raw_name = [x.text for x in tag_text]

    # keep only fruit name
        name_list = [name.split(' on')[0] for name in raw_name]

    # remove duplicates and output to new list 'final_fruit'
        final_fruit = []
        for fruitname in name_list:
            if fruitname not in final_fruit:
                final_fruit.append(fruitname)

     # make lists lengths match, fill space with blanks   
        for index in range(len(final_fruit), 200):
            final_fruit.append('')
            fruit_trees_df[zone_num] = True
 
    # create associated zone columns in Apples Dataframe each loop around   
        fruit_trees_df[cat] = final_fruit
        
#        fruit_trees_df['zone_' + zone_num] = True

https://www.cumminsnursery.com/buy-trees/index.php?type=tree&year=year1&view=list&zone=3&category=Apple&subcategory=
https://www.cumminsnursery.com/buy-trees/index.php?type=tree&year=year1&view=list&zone=3&category=Peach&subcategory=
https://www.cumminsnursery.com/buy-trees/index.php?type=tree&year=year1&view=list&zone=3&category=Plum&subcategory=
https://www.cumminsnursery.com/buy-trees/index.php?type=tree&year=year1&view=list&zone=3&category=Pear&subcategory=
https://www.cumminsnursery.com/buy-trees/index.php?type=tree&year=year1&view=list&zone=3&category=Nectarine&subcategory=
https://www.cumminsnursery.com/buy-trees/index.php?type=tree&year=year1&view=list&zone=3&category=Cherry&subcategory=
https://www.cumminsnursery.com/buy-trees/index.php?type=tree&year=year1&view=list&zone=3&category=Apricot&subcategory=

In [ ]:
# print dataframe to csv
# fruit_trees_df.to_csv('/home/nhac/Documents/NSS/Python/capstone/cummins_scrape_1.csv', index=False)

In [28]:
fruit_trees_df

,3,Apple,Peach,Plum,Pear,Nectarine,Cherry,Apricot
0,True,Almata,Veteran,Bubblegum,Flemish Beauty,,Meteor,
1,True,Antonovka (Common),,,Harrow Delight,,,
2,True,Black Oxford,,,Summercrisp,,,
3,True,Blue Pearmain,,,,,,
4,True,Centennial Crab,,,,,,
...,...,...,...,...,...,...,...,...
195,True,,,,,,,
196,True,,,,,,,
197,True,,,,,,,
198,True,,,,,,,
199,True,,,,,,,